# Site settings
author: Jack Locke
title: Data Science Adventures
header-img: img/home-bg.png
email: jackdlocke@gmail.com
copyright_name: Jack Locke
description: > # this means to ignore newlines until "baseurl:"
  My Journey
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  johnlocke333

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
